#!/bin/bash
# OTP Verification Flow Test Script
# Run this to see the complete OTP flow in action

echo "=========================================="
echo "OTP VERIFICATION SYSTEM - QUICK TEST"
echo "=========================================="
echo ""
echo "Start your server with:"
echo "  1. XAMPP Control Panel → Start Apache"
echo "  2. Open: http://localhost/interfaceauthtest/"
echo ""
echo "Test Flow:"
echo "  Step 1: Enter Student ID: 210009190"
echo "          Registration: 210009190"
echo "          Click 'Submit Details'"
echo ""
echo "  Step 2: Enter your email address"
echo "          Click 'SEND OTP'"
echo "          (Check Mailtrap inbox for OTP)"
echo ""
echo "  Step 3: Copy OTP from email"
echo "          Paste into 'Enter OTP Code'"
echo "          Click 'VERIFY OTP'"
echo ""
echo "  Step 4: View your webmail credentials!"
echo ""
echo "=========================================="
echo ""
echo "Check logs with:"
echo "  tail -f logs/app.log"
echo ""
echo "View Mailtrap inbox:"
echo "  https://mailtrap.io"
echo ""
echo "=========================================="
